name: JavaCI

on: [push, pull_request]

jobs:
  ubuntu_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8]
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: "zulu"
          # cache: "maven"
      - name: Build with gradle
        run: ./gradlew patch
